#!/usr/bin/env bash

[ $# -ne 1 ] && echo "Usage: $0 <install_dir>" && exit 1

INSTALL_DIR="$1"
TEMP_DIR="tmp/"

function clone_and_install(){
    if [ $# -lt 2 ]; then
      echo "Fatal error"
      return
    fi
    git clone https://$1/$2
    mkdir -p $2/build
    cd $2/build
    if [ $# -gt 2 ]; then
      git checkout $3
    fi
    cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" ..
    make
    make install
    cd ../../
}

mkdir -p "${TEMP_DIR}"
cd "${TEMP_DIR}" || (echo "FATAL: Cannot cd to ${TEMP_DIR}" && exit 1)

clone_and_install github.com/graeme-hill crossguid b151b7d1aeb68c4b9e98a8a2e0a547885aa0b60c

projects="
    clog
    crosssocket
    libcomm
    EventManager
    dot
    shell4cpp
"

for val in $projects; do
  clone_and_install github.com/bharatvaj "$val"
done
